apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline:1.0.0-12
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline:1.0.0-12
  template:
    metadata:
      labels:
        app: pipeline:1.0.0-12
    spec:
      containers:
      - name: pipeline:1.0.0-12
        image: saqlainkhan/pipeline:1.0.0-12
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080