apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-app 
  template:
    metadata:
      labels:
        app: pipeline-app
    spec:
      containers:
      - name: pipeline-app
        image: saqlainkhan/pipeline:1.0.0-11
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080